import os
from datetime import date
from pathlib import Path


def assign_tier(paper: dict) -> str:
    score = paper.get("relevance_score", 0)
    level = paper.get("evidence_level", "C")
    if score >= 8 and level == "A":
        return "🔴"
    elif score >= 6 and level in ("A", "B"):
        return "🟡"
    else:
        return "🔵"


def format_paper_entry(paper: dict) -> str:
    tier = assign_tier(paper)
    title = paper.get("title", "Untitled")
    authors = paper.get("authors", [])
    author_str = _format_authors(authors)
    journal = paper.get("journal", "")
    pub_date = paper.get("pub_date", "")
    evidence_level = paper.get("evidence_level", "C")
    study_design = paper.get("study_design", "unknown")
    methodology_flags = paper.get("methodology_flags", [])
    synthesis = paper.get("synthesis", paper.get("abstract", ""))
    url = paper.get("url", "")

    flags_str = ""
    if methodology_flags:
        flags_str = f" ⚠ {', '.join(methodology_flags)}"

    lines = [
        f"{tier} **{title}**",
        f"*{author_str} — {journal} ({pub_date})*",
        f"[{evidence_level} Evidence | {study_design}]{flags_str}",
        "",
        synthesis,
        "",
        f"[PubMed →]({url})",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _format_authors(authors: list[str]) -> str:
    if not authors:
        return "Author(s) unknown"
    if len(authors) <= 3:
        return ", ".join(authors)
    return f"{authors[0]}, {authors[1]}, {authors[2]} et al."


def format_newsletter(papers: list[dict], profile: dict, date_range: str) -> str:
    name = profile.get("name", "")
    specialties = ", ".join(profile.get("specialties", [])) or "General Medicine"
    roles = ", ".join(profile.get("role", [])) or "Physician"

    red = [p for p in papers if assign_tier(p) == "🔴"]
    yellow = [p for p in papers if assign_tier(p) == "🟡"]
    blue = [p for p in papers if assign_tier(p) == "🔵"]

    sections = []

    header = [
        "# Medical Research Digest",
        "",
        f"*{date_range}*",
    ]
    if name:
        header.append(f"*Generated for {name} | {specialties} | {roles}*")
    else:
        header.append(f"*Specialty focus: {specialties} | Role: {roles}*")
    header += [
        "",
        "## Summary",
        "",
        f"| Tier | Papers |",
        f"|------|--------|",
        f"| 🔴 High relevance, Level A evidence | {len(red)} |",
        f"| 🟡 Moderate relevance, Level A-B evidence | {len(yellow)} |",
        f"| 🔵 Worth watching, Level C / early stage | {len(blue)} |",
        "",
        "---",
        "",
    ]
    sections.append("\n".join(header))

    if red:
        sections.append("## 🔴 High Relevance | Evidence Level A\n")
        sections.extend(format_paper_entry(p) for p in red)

    if yellow:
        sections.append("## 🟡 Moderate Relevance | Evidence Level A-B\n")
        sections.extend(format_paper_entry(p) for p in yellow)

    if blue:
        sections.append("## 🔵 Worth Watching | Evidence Level C / Early Stage\n")
        sections.extend(format_paper_entry(p) for p in blue)

    gremial_notes = _collect_gremial_notes(papers)
    if gremial_notes:
        sections.append("## Upcoming in Your Field\n")
        sections.append(gremial_notes)
        sections.append("")

    sections.append(
        "---\n"
        "*Generated by med-research-digest · PubMed data via NCBI E-utilities*\n"
    )

    return "\n".join(sections)


def _collect_gremial_notes(papers: list[dict]) -> str:
    notes = []
    for paper in papers:
        gremial = paper.get("voice_outputs", {}).get("gremial_voice")
        if gremial:
            title = paper.get("title", "")[:80]
            notes.append(f"**Re: {title}...**\n{gremial}\n")
    return "\n".join(notes)


def save_newsletter(content: str, output_dir: str = "outputs") -> str:
    """Saves the newsletter to outputs/YYYY-MM-DD.md. Appends -2, -3 if file exists."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    today = date.today().strftime("%Y-%m-%d")
    base_path = Path(output_dir) / f"{today}.md"

    if not base_path.exists():
        path = base_path
    else:
        counter = 2
        while True:
            path = Path(output_dir) / f"{today}-{counter}.md"
            if not path.exists():
                break
            counter += 1

    path.write_text(content, encoding="utf-8")
    return str(path)
